# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'ReactiveExtension' do
  pod 'RxSwift', '~>5.0.0'
  pod 'RxCocoa', '~>5.0.0'
  
  abstract_target 'Infrastructure' do
    target 'AppleMusicCollector' do
      # Comment the next line if you don't want to use dynamic frameworks

      # Pods for AppleMusicCollector

      target 'AppleMusicCollectorTests' do
        inherit! :search_paths
        pod 'Nimble'
      end

      target 'AppleMusicCollectorUITests' do
        # Pods for testing
      end
    end
  end
end
